### ISSUE TITLE
Fake authentication for local development

### ISSUE THREAD

**Issue by jdpedrie** [fabiofenoglio/gin-cloudflare-access#1]
I'm interested in this package, but unsure how to effectively fake a login in a local development environment. I don't see anything in the README or API docs.

**Comment by fabiofenoglio** [comment]
Hello @jdpedrie, thank you for reporting the issue. I would kindly ask you to test the [release v0.2.2](https://github.com/fabiofenoglio/gin-cloudflare-access/releases/tag/v0.2.2) that I just published, were a new `AuthenticationFunc` configuration parameter has been introduced to help with mocking.

You can find some examples [in the main readme](https://github.com/fabiofenoglio/gin-cloudflare-access#mock-for-development-purposes)

**Comment by jdpedrie** [comment]
Thanks @fabiofenoglio! Worked fine, except that I found that `TokenExtractFunc` was not optional -- it has to return something besides an empty string, or the `buildAuthenticatorMiddleware` middleware returns before `AuthenticationFunc` is invoked.

Really appreciate the quick reply!

```go
		c.TokenExtractFunc = func(c *gin.Context) (string, error) {
			return "dummy token", nil
		}
```

**Comment by fabiofenoglio** [comment]
Yes, the `TokenExtractFunc` is optional in case you still plan on passing a token with the default headers and just want to mock the validation.

If you need to mock the whole authentication without passing any headers, using a `TokenExtractFunc` returning a fixed value as you did is the way to go.

Thank you for your feedback, I'm going to close this issue. Please don't hesitate to reach out as needed.
